import { useEffect, useRef, useState } from "react";
import type { PointerEvent } from "react";
import "./App.css";

const WS_URL="wss://canvasly-f0et.onrender.com",W=1200,H=700;
type Tool="select"|"pen"|"eraser"|"line"|"arrow"|"rectangle"|"circle"|"text"|"sticky";
type P={x:number;y:number};
type El={id:string;type:Exclude<Tool,"select">;points:P[];color:string;size:number;user:string;text?:string;fill?:boolean;font?:string;bold?:boolean;italic?:boolean;align?:string};
type User={id:string;name:string;color:string;drawing:boolean};
type Msg={type:string;[k:string]:any};
const roomOf=()=>new URLSearchParams(location.search).get("room")?.trim()||"main", roomKey=(r:string)=>`canvasly:${r}`, authKey="canvasly:account";
const clean=(s:string)=>s.trim().replace(/\s+/g,"-").replace(/[^a-zA-Z0-9_-]/g,"").slice(0,60)||"main";
function App(){
 const canvas=useRef<HTMLCanvasElement>(null),scroll=useRef<HTMLDivElement>(null),ws=useRef<WebSocket|null>(null),els=useRef<El[]>([]),nameRef=useRef("Guest"),clip=useRef<El[]>([]),active=useRef<string|null>(null),start=useRef<P|null>(null),drag=useRef<any>(null),textInput=useRef<HTMLInputElement>(null);
 const saved=(()=>{try{return JSON.parse(localStorage.getItem(authKey)||"null")}catch{return null}})();
 const [room,setRoom]=useState(roomOf),[roomInput,setRoomInput]=useState(roomOf),[name,setName]=useState(saved?.email?.split("@")[0]?.slice(0,20)||"Guest"),[tool,setTool]=useState<Tool>("pen"),[color,setColor]=useState("#111827"),[size,setSize]=useState(4),[fill,setFill]=useState(false),[elements,setElements]=useState<El[]>([]),[selected,setSelected]=useState<string[]>([]),[redo,setRedo]=useState<El[]>([]),[users,setUsers]=useState<User[]>([]),[status,setStatus]=useState("connecting"),[zoom,setZoom]=useState(1),[drawing,setDrawing]=useState(false),[cur,setCur]=useState<P|null>(null),[cursors,setCursors]=useState<Record<string,any>>({}),[showAI,setShowAI]=useState(false),[ai,setAI]=useState(""),[auth,setAuth]=useState(Boolean(saved)),[authMode,setAuthMode]=useState<"login"|"signup">("login"),[email,setEmail]=useState(saved?.email||""),[password,setPassword]=useState(""),[showPassword,setShowPassword]=useState(false),[space,setSpace]=useState(false),[notice,setNotice]=useState(""),[editing,setEditing]=useState<{tool:"text"|"sticky";x:number;y:number;value:string}|null>(null),[font,setFont]=useState("DM Sans"),[bold,setBold]=useState(false),[italic,setItalic]=useState(false),[textAlign,setTextAlign]=useState("left"),[stickyColor,setStickyColor]=useState("#f6d978");
 useEffect(()=>{els.current=elements},[elements]);useEffect(()=>{nameRef.current=name.trim()||"Guest"},[name]);useEffect(()=>{if(editing)textInput.current?.focus()},[editing]);
 const board=(n:El[])=>{els.current=n;setElements(n);try{localStorage.setItem(roomKey(room),JSON.stringify(n))}catch{}};const send=(m:object)=>{if(ws.current?.readyState===1)ws.current.send(JSON.stringify(m))};const op=(m:object)=>send({...m,opId:crypto.randomUUID()});
 const bounds=(e:El)=>{if(e.type==="circle"){const a=e.points[0],b=e.points.at(-1)||a,r=Math.max(1,Math.hypot(b.x-a.x,b.y-a.y));return{x:a.x-r,y:a.y-r,w:r*2,h:r*2}}if(e.type==="text"){const a=e.points[0];return{x:a.x,y:a.y-e.size*5,w:Math.max(40,(e.text||"").length*e.size*2.2),h:Math.max(24,e.size*6)}}const a=e.points[0],b=e.points.at(-1)||a;return{x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),w:Math.max(1,Math.abs(b.x-a.x)),h:Math.max(1,Math.abs(b.y-a.y))}};
 const draw=(c:CanvasRenderingContext2D,e:El)=>{if(!e.points.length)return;const a=e.points[0],b=e.points.at(-1)||a;c.lineWidth=e.size;c.lineCap="round";c.lineJoin="round";c.strokeStyle=e.type==="eraser"?"#fff":e.color;if(e.type==="text"){c.fillStyle=e.color;c.textAlign=(e.align||"left") as CanvasTextAlign;c.font=`${e.italic?"italic ":""}${e.bold?"700 ":"500 "}${Math.max(12,e.size*4)}px ${e.font||"DM Sans"}`;(e.text||"").split("\n").forEach((t,i)=>c.fillText(t,a.x,a.y+i*Math.max(16,e.size*5)));return}if(e.type==="sticky"){const x=Math.min(a.x,b.x),y=Math.min(a.y,b.y),w=Math.max(130,Math.abs(b.x-a.x)),h=Math.max(90,Math.abs(b.y-a.y));c.fillStyle=e.color;c.fillRect(x,y,w,h);c.strokeStyle="#4a3a2350";c.strokeRect(x,y,w,h);c.fillStyle="#29251f";c.textAlign="left";c.font=`${e.italic?"italic ":""}${e.bold?"700 ":"500 "}${Math.max(12,e.size*3)}px ${e.font||"Caveat"}`;(e.text||"Note").split("\n").forEach((t,i)=>c.fillText(t,x+14,y+28+i*Math.max(18,e.size*4)));return}c.beginPath();if(e.type==="pen"||e.type==="eraser"){c.moveTo(a.x,a.y);e.points.slice(1).forEach(p=>c.lineTo(p.x,p.y));c.stroke();return}if(e.type==="line"){c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();return}if(e.type==="arrow"){const ang=Math.atan2(b.y-a.y,b.x-a.x),head=Math.max(12,e.size*4);c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.moveTo(b.x,b.y);c.lineTo(b.x-head*Math.cos(ang-Math.PI/6),b.y-head*Math.sin(ang-Math.PI/6));c.moveTo(b.x,b.y);c.lineTo(b.x-head*Math.cos(ang+Math.PI/6),b.y-head*Math.sin(ang+Math.PI/6));c.stroke();return}if(e.type==="rectangle"){const x=Math.min(a.x,b.x),y=Math.min(a.y,b.y),w=Math.abs(b.x-a.x),h=Math.abs(b.y-a.y);if(e.fill){c.fillStyle=e.color;c.globalAlpha=.2;c.fillRect(x,y,w,h);c.globalAlpha=1}c.strokeRect(x,y,w,h);return}if(e.type==="circle"){const r=Math.hypot(b.x-a.x,b.y-a.y);if(e.fill){c.fillStyle=e.color;c.globalAlpha=.2;c.beginPath();c.arc(a.x,a.y,r,0,Math.PI*2);c.fill();c.globalAlpha=1}c.beginPath();c.arc(a.x,a.y,r,0,Math.PI*2);c.stroke()}};
 const redraw=()=>{const c=canvas.current,x=c?.getContext("2d");if(!c||!x)return;x.clearRect(0,0,W,H);x.fillStyle="#fffdf7";x.fillRect(0,0,W,H);els.current.forEach(e=>draw(x,e));selected.forEach(id=>{const e=els.current.find(a=>a.id===id);if(!e)return;const b=bounds(e);x.save();x.strokeStyle="#b68738";x.lineWidth=2;x.setLineDash([6,4]);x.strokeRect(b.x-5,b.y-5,b.w+10,b.h+10);x.setLineDash([]);[[b.x,b.y],[b.x+b.w,b.y],[b.x,b.y+b.h],[b.x+b.w,b.y+b.h]].forEach(([a,d])=>{x.fillStyle="#fff";x.fillRect(a-4,d-4,8,8);x.strokeRect(a-4,d-4,8,8)});x.restore()})};useEffect(()=>redraw(),[elements,selected,zoom]);
 useEffect(()=>{let stop=false;try{const c=JSON.parse(localStorage.getItem(roomKey(room))||"null");if(Array.isArray(c)){els.current=c;setElements(c)}}catch{}const connect=()=>{if(stop)return;setStatus("connecting");const s=new WebSocket(WS_URL);ws.current=s;s.onopen=()=>{setStatus("connected");send({type:"join",room,name:nameRef.current})};s.onmessage=e=>{try{const d:Msg=JSON.parse(e.data);if(d.type==="sync")board(d.elements||[]);else if(d.type==="presence")setUsers(d.users||[]);else if(d.type==="draw"&&d.element)board([...els.current.filter(x=>x.id!==d.element.id),d.element]);else if(d.type==="remove")board(els.current.filter(x=>x.id!==d.id));else if(d.type==="clear")board([]);else if(d.type==="cursor"&&d.id)setCursors(v=>({...v,[d.id]:d}));else if(d.type==="user_left")setCursors(v=>{const n={...v};delete n[d.id];return n})}catch{}};s.onclose=()=>{ws.current=null;if(!stop){setStatus("disconnected");setTimeout(connect,2500)}}};connect();return()=>{stop=true;ws.current?.close()}},[room]);
 const point=(e:PointerEvent<HTMLCanvasElement>):P=>{const r=canvas.current!.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H}};const hit=(p:P)=>{for(let i=els.current.length-1;i>=0;i--){const b=bounds(els.current[i]);if(p.x>=b.x-10&&p.x<=b.x+b.w+10&&p.y>=b.y-10&&p.y<=b.y+b.h+10)return els.current[i]}return null};
 const create=(a:P,b:P,text?:string):El=>({id:crypto.randomUUID(),type:tool,points:[a,b],color:tool==="sticky"?stickyColor:color,size,user:nameRef.current,text,fill,font,bold,italic,align:textAlign});
 const down=(e:PointerEvent<HTMLCanvasElement>)=>{const p=point(e);e.currentTarget.setPointerCapture(e.pointerId);if(space){drag.current={pan:true,sx:e.clientX,sy:e.clientY,l:scroll.current?.scrollLeft||0,t:scroll.current?.scrollTop||0};return}if(tool==="text"||tool==="sticky"){setEditing({tool,x:p.x,y:p.y,value:""});return}if(tool==="select"){const h=hit(p);if(h){if(e.shiftKey)setSelected(s=>s.includes(h.id)?s.filter(x=>x!==h.id):[...s,h.id]);else setSelected([h.id]);drag.current={start:p,originals:els.current.filter(x=>selected.includes(x.id)||x.id===h.id)}}else if(!e.shiftKey)setSelected([]);return}setDrawing(true);start.current=p;setCur(p);send({type:"activity",room,drawing:true});if(tool==="pen"||tool==="eraser"){const x=create(p,p);active.current=x.id;board([...els.current,x])}};
 const move=(e:PointerEvent<HTMLCanvasElement>)=>{const p=point(e);if(space&&drag.current?.pan){const s=scroll.current;if(s){s.scrollLeft=drag.current.l-(e.clientX-drag.current.sx);s.scrollTop=drag.current.t-(e.clientY-drag.current.sy)}return}if(tool==="select"&&drag.current?.originals){const dx=p.x-drag.current.start.x,dy=p.y-drag.current.start.y,ids=new Set(drag.current.originals.map((x:El)=>x.id));board(els.current.map(x=>ids.has(x.id)?{...x,points:x.points.map(q=>({x:q.x+dx,y:q.y+dy}))}:x));return}if(!drawing)return;setCur(p);if((tool==="pen"||tool==="eraser")&&active.current)board(els.current.map(x=>x.id===active.current?{...x,points:[...x.points,p]}:x))};
 const up=()=>{if(space){drag.current=null;return}if(tool==="select"){if(drag.current?.originals)drag.current.originals.forEach((o:El)=>{const n=els.current.find(x=>x.id===o.id);if(n)op({type:"draw",room,element:n})});drag.current=null;return}if(!drawing)return;if(start.current&&cur){const x=create(start.current,cur);board([...els.current,x]);op({type:"draw",room,element:x})}else if(active.current){const x=els.current.find(a=>a.id===active.current);if(x)op({type:"draw",room,element:x})}active.current=null;start.current=null;setCur(null);setDrawing(false);send({type:"activity",room,drawing:false})};
 const finishEditing=()=>{if(!editing?.value.trim()){setEditing(null);return}const a={x:editing.x,y:editing.y},b=editing.tool==="sticky"?{x:a.x+250,y:a.y+150}:{x:a.x+Math.max(100,editing.value.length*size*2.2),y:a.y+35};const x={...create(a,b,editing.value.trim()),type:editing.tool,color:editing.tool==="sticky"?stickyColor:color,font:bold?font:font,bold,italic,align:textAlign};board([...els.current,x]);op({type:"draw",room,element:x});setEditing(null)};
 const remove=()=>{if(!selected.length)return;selected.forEach(id=>op({type:"remove",room,id}));board(els.current.filter(x=>!selected.includes(x.id)));setSelected([])};const copy=()=>{clip.current=els.current.filter(x=>selected.includes(x.id)).map(x=>({...x,points:x.points.map(p=>({...p}))}))};const paste=()=>{const a=clip.current.map(x=>({...x,id:crypto.randomUUID(),user:nameRef.current,points:x.points.map(p=>({x:p.x+30,y:p.y+30}))}));if(!a.length)return;board([...els.current,...a]);setSelected(a.map(x=>x.id));a.forEach(x=>op({type:"draw",room,element:x}))};const removeOne=(id:string)=>{op({type:"remove",room,id});board(els.current.filter(x=>x.id!==id));setSelected([])};const undo=()=>{const x=els.current.filter(x=>x.user===nameRef.current).at(-1);if(x){removeOne(x.id);setRedo(r=>[...r,x])}};const redoOne=()=>{const x=redo.at(-1);if(x){board([...els.current,x]);op({type:"draw",room,element:x});setRedo(r=>r.slice(0,-1))}};
 const aiText=()=>{const counts=elements.reduce((a,e)=>(a[e.type]=(a[e.type]||0)+1,a),{} as Record<string,number>);if(!elements.length)return"Your board is empty. Add a goal, idea, decision or next step.";return `Your board has ${elements.length} objects. ${counts.sticky?`You have ${counts.sticky} notes—group them into themes. `:""}${counts.arrow||counts.line?"Your connections can become a clear Start → Process → Result flow.":"Try adding arrows between related ideas."}`};
 useEffect(()=>{const k=(e:KeyboardEvent)=>{const m=e.ctrlKey||e.metaKey;if(editing){if(e.key==="Escape"){setEditing(null);return}if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();finishEditing();return}}if(e.code==="Space"&&!e.repeat){setSpace(true);e.preventDefault()}if(m&&e.key.toLowerCase()==="z"){e.preventDefault();undo()}else if(m&&e.key.toLowerCase()==="y"){e.preventDefault();redoOne()}else if(m&&e.key.toLowerCase()==="c"&&selected.length){e.preventDefault();copy()}else if(m&&e.key.toLowerCase()==="v"){e.preventDefault();paste()}else if((e.key==="Delete"||e.key==="Backspace")&&selected.length){e.preventDefault();remove()}};const u=(e:KeyboardEvent)=>{if(e.code==="Space")setSpace(false)};addEventListener("keydown",k);addEventListener("keyup",u);return()=>{removeEventListener("keydown",k);removeEventListener("keyup",u)}},[editing,selected,redo,elements]);
 const switchRoom=()=>{const r=clean(roomInput);history.pushState({},"",`?room=${encodeURIComponent(r)}`);setRoom(r);setSelected([])};const share=async()=>{const u=`${location.origin}${location.pathname}?room=${encodeURIComponent(room)}`;try{await navigator.clipboard.writeText(u);setNotice("Room link copied")}catch{setNotice(u)}};const exportPNG=()=>{const a=document.createElement("a");a.download=`canvasly-${room}.png`;a.href=canvas.current!.toDataURL();a.click()};const fit=()=>setZoom(Math.min(1.5,Math.max(.5,((scroll.current?.clientWidth||W)-40)/W)));
 const doAuth=()=>{if(!email||password.length<4){setNotice("Enter an email and a password with at least 4 characters");return}localStorage.setItem(authKey,JSON.stringify({email,password}));setAuth(true);setName(email.split("@")[0].slice(0,20)||"Guest")};
 const tools:[Tool,string][]=[["select","Select"],["pen","Pen"],["eraser","Eraser"],["line","Line"],["arrow","Arrow"],["rectangle","Rect"],["circle","Circle"],["text","Text"],["sticky","Sticky"]];
 if(!auth)return <div className="auth-screen"><div className="auth-art"><div className="art-logo">✦</div><div className="art-copy"><span>MAKE SPACE FOR IDEAS</span><h2>Draw it.<br/>Shape it.<br/><em>Together.</em></h2><p>A shared canvas for sketches, plans, wild ideas and everything in between.</p></div><div className="doodle d1">↗</div><div className="doodle d2">○</div><div className="doodle d3">✎</div><div className="art-line"/></div><div className="auth-card"><div className="auth-kicker">CANVASLY</div><h1>{authMode==="login"?"Welcome back":"Start creating"}</h1><p className="auth-sub">{authMode==="login"?"Pick up where your ideas left off.":"Create your space and bring ideas together."}</p><div className="auth-tabs"><button className={authMode==="login"?"active":""} onClick={()=>setAuthMode("login")}>Sign in</button><button className={authMode==="signup"?"active":""} onClick={()=>setAuthMode("signup")}>Create account</button></div><label className="field"><span>Email</span><input placeholder="you@example.com" type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="field"><span>Password</span><div className="password-wrap"><input placeholder="Your password" type={showPassword?"text":"password"} value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==="Enter"&&doAuth()}/><button type="button" className="password-toggle" onClick={()=>setShowPassword(v=>!v)}>{showPassword?"Hide":"Show"}</button></div></label><button className="primary auth-submit" onClick={doAuth}>{authMode==="signup"?"Create account":"Sign in"}<span>→</span></button><div className="auth-foot"><span>Private room workspace</span><span>•</span><span>Realtime collaboration</span></div></div></div>;
 return <div className="app"><header className="topbar"><div className="brand"><div className="logo">✦</div><div><h1>Canvasly</h1><span>Collaborative canvas</span></div></div><div className="connection"><i className={status}/>{status}</div><div className="top-actions"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/><input className="room-input" value={roomInput} onChange={e=>setRoomInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&switchRoom()}/><button onClick={switchRoom}>Join</button><button onClick={share}>Share</button><button onClick={()=>setShowAI(v=>!v)} className="ai-btn">✦ AI</button><button onClick={()=>{localStorage.removeItem(authKey);setAuth(false)}}>Sign out</button></div></header>
 <nav className="toolbar"><div className="tool-group">{tools.map(([id,label])=><button key={id} className={tool===id?"tool active":"tool"} onClick={()=>setTool(id)}>{label}</button>)}</div><span className="divider"/>{(tool==="text"||tool==="sticky")&&<><label>Font <select value={font} onChange={e=>setFont(e.target.value)}><option>DM Sans</option><option>Georgia</option><option>Playfair Display</option><option>Caveat</option><option>Courier New</option></select></label><label>Size <input type="range" min="3" max="18" value={size} onChange={e=>setSize(+e.target.value)}/></label><button className={bold?"format active":"format"} onClick={()=>setBold(v=>!v)}><b>B</b></button><button className={italic?"format active":"format"} onClick={()=>setItalic(v=>!v)}><i>I</i></button>{tool==="text"&&<label>Align <select value={textAlign} onChange={e=>setTextAlign(e.target.value)}><option value="left">Left</option><option value="center">Center</option><option value="right">Right</option></select></label>}{tool==="sticky"&&<label>Paper <input type="color" value={stickyColor} onChange={e=>setStickyColor(e.target.value)}/></label>}</>}<span className="divider"/><label>Color <input type="color" value={color} onChange={e=>setColor(e.target.value)}/></label><label className="size">Size {size}<input type="range" min="1" max="18" value={size} onChange={e=>setSize(+e.target.value)}/></label><label><input type="checkbox" checked={fill} onChange={e=>setFill(e.target.checked)}/> Fill</label><span className="divider"/><button onClick={undo}>↶ Undo</button><button onClick={redoOne}>↷ Redo</button><button onClick={copy}>Copy</button><button onClick={paste}>Paste</button><button onClick={remove}>Delete</button><button onClick={()=>setZoom(z=>Math.max(.5,z-.1))}>−</button><b>{Math.round(zoom*100)}%</b><button onClick={()=>setZoom(z=>Math.min(2,z+.1))}>+</button><button onClick={fit}>Fit</button><button onClick={exportPNG}>Export PNG</button></nav>
 {showAI&&<aside className="ai-panel"><strong>✦ Canvasly AI Assistant</strong><p>{ai||"A quick second pair of eyes for your board."}</p><button onClick={()=>setAI(aiText())}>Analyze board</button><button onClick={()=>setAI("Try a simple flow: goal → ideas → priorities → decision → next step.")}>Suggest workflow</button><button onClick={()=>setAI("Keep labels short, group related notes, and use arrows only where they clarify a relationship.")}>Improve layout</button></aside>}
 <main className="workspace"><div className="canvas-card"><div className="canvas-head"><span>Room <b>#{room}</b></span><span>{users.length||1} collaborator{users.length===1?"":"s"} • {elements.length} objects</span></div><div className="canvas-scroll" ref={scroll}><div className="stage" style={{width:W*zoom,height:H*zoom}}><canvas ref={canvas} width={W} height={H} className="canvas" style={{width:W*zoom,height:H*zoom}} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerLeave={up}/>{Object.values(cursors).map((c:any)=><div key={c.id} className="remote" style={{left:c.x*zoom,top:c.y*zoom,"--c":c.color} as any}>➤ <span>{c.name}</span></div>)}{editing&&<input ref={textInput} className="canvas-editor" value={editing.value} onChange={e=>setEditing(v=>v?{...v,value:e.target.value}:v)} onKeyDown={e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();finishEditing()}if(e.key==="Escape")setEditing(null)}} style={{left:editing.x*zoom,top:(editing.y-18)*zoom,fontFamily:font,fontSize:Math.max(16,size*4)*zoom,fontWeight:bold?700:500,fontStyle:italic?"italic":"normal",color:editing.tool==="sticky"?"#29251f":color,background:editing.tool==="sticky"?stickyColor:"transparent",width:editing.tool==="sticky"?250*zoom:360*zoom,minHeight:editing.tool==="sticky"?90*zoom:45*zoom}} placeholder={editing.tool==="sticky"?"Write a note…":"Type here…"}/>}</div></div></div></main><footer><span>⌨️ Space + drag to pan • Ctrl/Cmd Z/Y/C/V • Delete</span><span>Realtime rooms • persistent boards</span></footer>{notice&&<button className="toast" onClick={()=>setNotice("")}>{notice}</button>}</div>;
}
export default App;
