import { useEffect, useMemo, useRef, useState } from "react";
import type { PointerEvent } from "react";
import "./App.css";
import "./sidebar.css";
import "./ui-fix.css";

const WS_URL = "wss://canvasly-f0et.onrender.com";
const W = 1200, H = 700;
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL || "";
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY || import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY || "";

type Tool = "select"|"pen"|"eraser"|"line"|"arrow"|"rectangle"|"rounded"|"circle"|"triangle"|"diamond"|"star"|"text"|"sticky"|"image";
type P = {x:number;y:number};
type El = {id:string;type:Exclude<Tool,"select">;points:P[];color:string;size:number;user:string;text?:string;fill?:boolean;font?:string;bold?:boolean;italic?:boolean;align?:string;textColor?:string;src?:string};
type User = {id:string;name:string;color:string;drawing:boolean};
type Comment = {id:string;user:string,color:string,text:string,x:number,y:number,createdAt:number,reactions:Record<string,string[]>};
type Msg = {type:string;[k:string]:any};
const roomOf=()=>new URLSearchParams(location.search).get("room")?.trim()||"main";
const roomKey=(r:string)=>`canvasly:${r}`;
const clean=(s:string)=>s.trim().replace(/\s+/g,"-").replace(/[^a-zA-Z0-9_-]/g,"").slice(0,60)||"main";

async function authRequest(path:string,body:any){
 if(!SUPABASE_URL||!SUPABASE_KEY) throw new Error("Supabase Auth is not configured. Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in Vercel.");
 const r=await fetch(`${SUPABASE_URL}/auth/v1/${path}`,{method:"POST",headers:{apikey:SUPABASE_KEY,"Content-Type":"application/json"},body:JSON.stringify(body)});
 const d=await r.json().catch(()=>({})); if(!r.ok) throw new Error(d.msg||d.error_description||d.message||"Authentication failed"); return d;
}

function App(){
 const canvas=useRef<HTMLCanvasElement>(null),scroll=useRef<HTMLDivElement>(null),ws=useRef<WebSocket|null>(null),els=useRef<El[]>([]),active=useRef<string|null>(null),start=useRef<P|null>(null),drag=useRef<any>(null),textInput=useRef<HTMLTextAreaElement>(null),fileInput=useRef<HTMLInputElement>(null),nameRef=useRef("Guest"),clip=useRef<El[]>([]);
 const [room,setRoom]=useState(roomOf()),[roomInput,setRoomInput]=useState(roomOf()),[tool,setTool]=useState<Tool>("pen"),[color,setColor]=useState("#18222b"),[size,setSize]=useState(4),[fill,setFill]=useState(false),[elements,setElements]=useState<El[]>([]),[selected,setSelected]=useState<string[]>([]),[redo,setRedo]=useState<El[]>([]),[users,setUsers]=useState<User[]>([]),[status,setStatus]=useState("connecting"),[zoom,setZoom]=useState(1),[drawing,setDrawing]=useState(false),[cur,setCur]=useState<P|null>(null),[cursors,setCursors]=useState<Record<string,any>>({}),[showAI,setShowAI]=useState(false),[ai,setAI]=useState(""),[auth,setAuth]=useState(false),[authMode,setAuthMode]=useState<"login"|"signup">("login"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[authBusy,setAuthBusy]=useState(false),[authError,setAuthError]=useState(""),[session,setSession]=useState<any>(null),[editing,setEditing]=useState<{tool:"text"|"sticky";x:number;y:number;value:string}|null>(null),[font,setFont]=useState("DM Sans"),[bold,setBold]=useState(false),[italic,setItalic]=useState(false),[textAlign,setTextAlign]=useState("left"),[stickyColor,setStickyColor]=useState("#f6d978"),[stickyTextColor,setStickyTextColor]=useState("#29251f"),[showComments,setShowComments]=useState(false),[comments,setComments]=useState<Comment[]>([]),[commentText,setCommentText]=useState("");
 const userName=useMemo(()=>session?.user?.user_metadata?.name||session?.user?.email?.split("@")[0]||"Guest",[session]);
 useEffect(()=>{nameRef.current=userName},[userName]);
 useEffect(()=>{try{const s=JSON.parse(localStorage.getItem("canvasly:supabase-session")||"null");if(s?.access_token){setSession(s);setAuth(true)}}catch{}},[]);
 const board=(n:El[])=>{els.current=n;setElements(n);try{localStorage.setItem(roomKey(room),JSON.stringify(n))}catch{}};
 const send=(m:object)=>{if(ws.current?.readyState===1)ws.current.send(JSON.stringify(m))};
 const op=(m:object)=>send({...m,opId:crypto.randomUUID()});
 const bounds=(e:El)=>{const a=e.points[0],b=e.points.at(-1)||a;if(e.type==="circle"){const r=Math.max(1,Math.hypot(b.x-a.x,b.y-a.y));return{x:a.x-r,y:a.y-r,w:r*2,h:r*2}}if(e.type==="text"){const lines=(e.text||"").split("\n");return{x:a.x,y:a.y-e.size*5,w:Math.max(40,...lines.map(t=>t.length*e.size*2.2)),h:Math.max(24,lines.length*e.size*5+8)}}return{x:Math.min(a.x,b.x),y:Math.min(a.y,b.y),w:Math.max(1,Math.abs(b.x-a.x)),h:Math.max(1,Math.abs(b.y-a.y))}};
 const draw=(c:CanvasRenderingContext2D,e:El)=>{if(!e.points.length)return;const a=e.points[0],b=e.points.at(-1)||a;c.lineWidth=e.size;c.lineCap="round";c.lineJoin="round";c.strokeStyle=e.type==="eraser"?"#fff":e.color;
  if(e.type==="image"&&e.src){const im=new Image();im.onload=()=>{const x=Math.min(a.x,b.x),y=Math.min(a.y,b.y),w=Math.max(20,Math.abs(b.x-a.x)),h=Math.max(20,Math.abs(b.y-a.y));c.drawImage(im,x,y,w,h)};im.src=e.src;return}
  if(e.type==="text"){c.fillStyle=e.color;c.textAlign=(e.align||"left") as CanvasTextAlign;c.font=`${e.italic?"italic ":""}${e.bold?"700 ":"500 "}${Math.max(12,e.size*4)}px ${e.font||"DM Sans"}`;(e.text||"").split("\n").forEach((t,i)=>c.fillText(t,a.x,a.y+i*Math.max(16,e.size*5)));return}
  if(e.type==="sticky"){const x=Math.min(a.x,b.x),y=Math.min(a.y,b.y),w=Math.max(130,Math.abs(b.x-a.x)),h=Math.max(90,Math.abs(b.y-a.y));c.fillStyle=e.color;c.fillRect(x,y,w,h);c.strokeStyle="#4a3a2350";c.strokeRect(x,y,w,h);c.fillStyle=e.textColor||"#29251f";c.textAlign=(e.align||"left") as CanvasTextAlign;c.font=`${e.italic?"italic ":""}${e.bold?"700 ":"500 "}${Math.max(12,e.size*3)}px ${e.font||"Caveat"}`;(e.text||"Note").split("\n").forEach((t,i)=>c.fillText(t,(e.align||"left")==="center"?x+w/2:(e.align||"left")==="right"?x+w-14:x+14,y+28+i*Math.max(18,e.size*4)));return}
  if(e.type==="pen"||e.type==="eraser"){c.beginPath();c.moveTo(a.x,a.y);e.points.slice(1).forEach(p=>c.lineTo(p.x,p.y));c.stroke();return}
  if(e.type==="line"){c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();return}
  if(e.type==="arrow"){const ang=Math.atan2(b.y-a.y,b.x-a.x),head=Math.max(12,e.size*4);c.beginPath();c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.moveTo(b.x,b.y);c.lineTo(b.x-head*Math.cos(ang-Math.PI/6),b.y-head*Math.sin(ang-Math.PI/6));c.moveTo(b.x,b.y);c.lineTo(b.x-head*Math.cos(ang+Math.PI/6),b.y-head*Math.sin(ang+Math.PI/6));c.stroke();return}
  const x=Math.min(a.x,b.x),y=Math.min(a.y,b.y),w=Math.abs(b.x-a.x),h=Math.abs(b.y-a.y);if(e.fill){c.fillStyle=e.color;c.globalAlpha=.2;c.beginPath();if(e.type==="circle")c.arc(a.x,a.y,Math.hypot(b.x-a.x,b.y-a.y),0,Math.PI*2);else c.rect(x,y,w,h);c.fill();c.globalAlpha=1}
  c.beginPath();if(e.type==="circle")c.arc(a.x,a.y,Math.hypot(b.x-a.x,b.y-a.y),0,Math.PI*2);else if(e.type==="triangle"){c.moveTo(x+w/2,y);c.lineTo(x+w,y+h);c.lineTo(x,y+h);c.closePath()}else if(e.type==="diamond"){c.moveTo(x+w/2,y);c.lineTo(x+w,y+h/2);c.lineTo(x+w/2,y+h);c.lineTo(x,y+h/2);c.closePath()}else if(e.type==="star"){for(let i=0;i<10;i++){const r=i%2?w/2:w/4,ang=-Math.PI/2+i*Math.PI/5;c.lineTo(x+w/2+Math.cos(ang)*r,y+h/2+Math.sin(ang)*Math.min(r,h/2))}c.closePath()}else if(e.type==="rounded"){c.roundRect(x,y,w,h,16)}else c.rect(x,y,w,h);c.stroke();
 };
 const redraw=()=>{const c=canvas.current,x=c?.getContext("2d");if(!c||!x)return;x.clearRect(0,0,W,H);x.fillStyle="#fffdf7";x.fillRect(0,0,W,H);els.current.forEach(e=>draw(x,e));selected.forEach(id=>{const e=els.current.find(a=>a.id===id);if(!e)return;const b=bounds(e);x.save();x.strokeStyle="#b68738";x.lineWidth=2;x.setLineDash([6,4]);x.strokeRect(b.x-5,b.y-5,b.w+10,b.h+10);x.setLineDash([]);x.restore()})};
 useEffect(()=>redraw(),[elements,selected,zoom]);
 useEffect(()=>{if(!auth)return;let stop=false;try{const c=JSON.parse(localStorage.getItem(roomKey(room))||"null");if(Array.isArray(c))board(c)}catch{};const connect=()=>{if(stop)return;setStatus("connecting");const s=new WebSocket(WS_URL);ws.current=s;s.onopen=()=>{setStatus("connected");send({type:"join",room,name:nameRef.current})};s.onmessage=e=>{try{const d:Msg=JSON.parse(e.data);if(d.type==="sync"){board(d.elements||[]);setComments(d.comments||[])}else if(d.type==="presence")setUsers(d.users||[]);else if(d.type==="draw"&&d.element)board([...els.current.filter(x=>x.id!==d.element.id),d.element]);else if(d.type==="remove")board(els.current.filter(x=>x.id!==d.id));else if(d.type==="clear")board([]);else if(d.type==="cursor"&&d.id)setCursors(v=>({...v,[d.id]:d}));else if(d.type==="user_left")setCursors(v=>{const n={...v};delete n[d.id];return n});else if(d.type==="comment")setComments(v=>v.some(x=>x.id===d.comment.id)?v:v.concat(d.comment));else if(d.type==="reaction")setComments(v=>v.map(c=>c.id===d.commentId?{...c,reactions:d.reactions}:c))}catch{}};s.onclose=()=>{ws.current=null;if(!stop){setStatus("disconnected");setTimeout(connect,2500)}}};connect();return()=>{stop=true;ws.current?.close()}},[room,auth]);
 const point=(e:PointerEvent<HTMLCanvasElement>):P=>{const r=canvas.current!.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H}};
 const hit=(p:P)=>{for(let i=els.current.length-1;i>=0;i--){const b=bounds(els.current[i]);if(p.x>=b.x-10&&p.x<=b.x+b.w+10&&p.y>=b.y-10&&p.y<=b.y+b.h+10)return els.current[i]}return null};
 const create=(a:P,b:P,text?:string):El=>({id:crypto.randomUUID(),type:tool as Exclude<Tool,"select">,points:[a,b],color:tool==="sticky"?stickyColor:color,size,user:nameRef.current,text,fill,font,bold,italic,align:textAlign,textColor:tool==="sticky"?stickyTextColor:color});
 const down=(e:PointerEvent<HTMLCanvasElement>)=>{const p=point(e);e.currentTarget.setPointerCapture(e.pointerId);if(tool==="text"||tool==="sticky"){setEditing({tool,x:p.x,y:p.y,value:""});return}if(tool==="image"){fileInput.current?.click();return}if(tool==="select"){const h=hit(p);if(h){setSelected(e.shiftKey?s=>s.includes(h.id)?s.filter(x=>x!==h.id):[...s,h.id]:[h.id]);drag.current={start:p,ids:new Set(e.shiftKey?selected:[h.id])}}else setSelected([]);return}setDrawing(true);start.current=p;setCur(p);if(tool==="pen"||tool==="eraser"){const x=create(p,p);active.current=x.id;board([...els.current,x])}};
 const move=(e:PointerEvent<HTMLCanvasElement>)=>{const p=point(e);if(tool==="select"&&drag.current){const dx=p.x-drag.current.start.x,dy=p.y-drag.current.start.y;board(els.current.map(x=>drag.current.ids.has(x.id)?{...x,points:x.points.map(q=>({x:q.x+dx,y:q.y+dy}))}:x));return}if(!drawing)return;setCur(p);if((tool==="pen"||tool==="eraser")&&active.current)board(els.current.map(x=>x.id===active.current?{...x,points:[...x.points,p]}:x))};
 const up=()=>{if(tool==="select"){if(drag.current)drag.current=null;return}if(!drawing)return;if(start.current&&cur){const x=create(start.current,cur);board([...els.current,x]);op({type:"draw",room,element:x})}else if(active.current){const x=els.current.find(a=>a.id===active.current);if(x)op({type:"draw",room,element:x})}active.current=null;start.current=null;setCur(null);setDrawing(false)};
 const finishEditing=()=>{if(!editing?.value.trim()){setEditing(null);return}const a={x:editing.x,y:editing.y},b=editing.tool==="sticky"?{x:a.x+250,y:a.y+150}:{x:a.x+Math.max(100,editing.value.length*size*2.2),y:a.y+Math.max(35,editing.value.split("\n").length*size*5)};const x={...create(a,b,editing.value.trim()),type:editing.tool};board([...els.current,x]);op({type:"draw",room,element:x});setEditing(null)};
 const uploadImage=(file:File)=>{const r=new FileReader();r.onload=()=>{const src=String(r.result),x:El={id:crypto.randomUUID(),type:"image",points:[{x:100,y:100},{x:450,y:350}],color,size,user:nameRef.current,src};board([...els.current,x]);op({type:"draw",room,element:x})};r.readAsDataURL(file)};
 const remove=()=>{selected.forEach(id=>op({type:"remove",room,id}));board(els.current.filter(x=>!selected.includes(x.id)));setSelected([])};
 const clear=()=>{op({type:"clear",room});board([]);setSelected([])};
 const copy=()=>{clip.current=els.current.filter(x=>selected.includes(x.id)).map(x=>({...x,points:x.points.map(p=>({...p}))}))};const paste=()=>{const a=clip.current.map(x=>({...x,id:crypto.randomUUID(),points:x.points.map(p=>({x:p.x+30,y:p.y+30}))}));board([...els.current,...a]);a.forEach(x=>op({type:"draw",room,element:x}))};
 const submitAuth=async(e:any)=>{e.preventDefault();setAuthBusy(true);setAuthError("");try{const d=await authRequest(authMode==="signup"?"signup":"token?grant_type=password",authMode==="signup"?{email,password,options:{data:{name:email.split("@")[0]}}}:{email,password});if(authMode==="signup"&&!d.access_token){setAuthError("Account created. Check your email to confirm, then sign in.")}else{const s=d;localStorage.setItem("canvasly:supabase-session",JSON.stringify(s));setSession(s);setAuth(true)}}catch(err:any){setAuthError(err.message)}finally{setAuthBusy(false)}};
 const logout=()=>{localStorage.removeItem("canvasly:supabase-session");setSession(null);setAuth(false);ws.current?.close()};
 const addComment=()=>{if(!commentText.trim())return;const c:Comment={id:crypto.randomUUID(),user:nameRef.current,color:"#b68738",text:commentText.trim(),x:80,y:80,createdAt:Date.now(),reactions:{}};setComments(v=>[...v,c]);send({type:"comment",room,comment:c});setCommentText("")};
 const react=(id:string,emoji:string)=>{const c=comments.find(x=>x.id===id);if(!c)return;const old=c.reactions[emoji]||[],next=old.includes(nameRef.current)?old.filter(x=>x!==nameRef.current):[...old,nameRef.current],reactions={...c.reactions,[emoji]:next};setComments(v=>v.map(x=>x.id===id?{...x,reactions}:x));send({type:"reaction",room,commentId:id,reactions})};
 const tools:[Tool,string][]=[["select","Select"],["pen","Pen"],["eraser","Erase"],["line","Line"],["arrow","Arrow"],["rectangle","Rect"],["rounded","Round"],["circle","Circle"],["triangle","Triangle"],["diamond","Diamond"],["star","Star"],["text","Text"],["sticky","Sticky"],["image","Image"]];
 if(!auth)return <div className="auth-screen"><section className="auth-brand"><div className="brand-mark">C</div><h1>Canvasly</h1><p>Real-time collaborative thinking space.</p><div className="auth-points"><span>Live multiplayer canvas</span><span>Notes, shapes and images</span><span>Comments and reactions</span></div></section><form className="auth-card" onSubmit={submitAuth}><div className="eyebrow">WORKSPACE ACCESS</div><h2>{authMode==="login"?"Welcome back":"Create your workspace"}</h2><p>{authMode==="login"?"Sign in to continue collaborating.":"Create a secure Canvasly account."}</p>{authError&&<div className="auth-error">{authError}</div>}<label>Email<input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/></label><label>Password<input type="password" minLength={6} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="At least 6 characters"/></label><button className="primary" disabled={authBusy}>{authBusy?"Working…":authMode==="login"?"Sign in":"Create account"}</button><button type="button" className="text-button" onClick={()=>{setAuthMode(authMode==="login"?"signup":"login");setAuthError("")}}>{authMode==="login"?"Create an account":"Already have an account? Sign in"}</button><small>Authentication uses Supabase Auth; passwords are never stored in Canvasly localStorage.</small></form></div>;
 return <div className="app"><header className="topbar"><div className="brand"><div className="brand-mark">C</div><strong>Canvasly</strong></div><div className="room-controls"><input value={roomInput} onChange={e=>setRoomInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&setRoom(clean(roomInput))}/><button onClick={()=>setRoom(clean(roomInput))}>Open room</button><span className={`status ${status}`}>{status}</span></div><div className="top-actions"><button onClick={()=>setShowComments(v=>!v)}>Comments</button><button onClick={()=>setShowAI(v=>!v)}>AI</button><span className="avatar">{nameRef.current[0]?.toUpperCase()}</span><button onClick={logout}>Sign out</button></div></header>
 <aside className="toolbar"><div className="rail-title">TOOLS</div>{tools.map(([t,label])=><button key={t} className={`tool ${tool===t?"active":""}`} onClick={()=>{setTool(t);if(t==="image")fileInput.current?.click()}} title={label}>{label}</button>)}<div className="divider"/><label>Size <input type="range" min="1" max="20" value={size} onChange={e=>setSize(+e.target.value)}/></label><label>Ink <input type="color" value={color} onChange={e=>setColor(e.target.value)}/></label><label><input type="checkbox" checked={fill} onChange={e=>setFill(e.target.checked)}/> Fill</label><button onClick={()=>setZoom(Math.max(.5,zoom-.1))}>− Zoom</button><button onClick={()=>setZoom(Math.min(2,zoom+.1))}>+ Zoom</button><button onClick={remove}>Delete</button><button onClick={clear}>Clear board</button></aside>
 <main className="workspace"><div className="canvas-wrap" ref={scroll}><div className="canvas-stage" style={{width:W*zoom,height:H*zoom}}><canvas ref={canvas} width={W} height={H} className="canvas" style={{width:W*zoom,height:H*zoom}} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerLeave={()=>setCur(null)} onPointerMoveCapture={e=>{const p=point(e);send({type:"cursor",room,x:p.x,y:p.y})}}/>{editing&&<textarea ref={textInput} className="canvas-editor" style={{left:editing.x*zoom,top:(editing.y-editing.tool==="text"?20:0)*zoom,width:editing.tool==="sticky"?250*zoom:320*zoom,minHeight:editing.tool==="sticky"?150*zoom:70*zoom,fontFamily:font,fontWeight:bold?700:500,fontStyle:italic?"italic":"normal",textAlign:textAlign as any,background:editing.tool==="sticky"?stickyColor:"#fff"}} value={editing.value} placeholder={editing.tool==="sticky"?"Write your note…":"Type on the canvas…"} onChange={e=>setEditing(v=>v?{...v,value:e.target.value}:v)} onKeyDown={e=>{if(e.key==="Escape")setEditing(null);if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();finishEditing()}}} onBlur={finishEditing}/>}</div></div><div className="collab-strip"><span>{users.length} collaborator{users.length===1?"":"s"}</span>{users.slice(0,7).map(u=><span key={u.id} className="collab-avatar" title={u.name}>{u.name[0]?.toUpperCase()}</span>)}<span className="room-label">Room: {room}</span></div></main>
 <input ref={fileInput} hidden type="file" accept="image/png,image/jpeg,image/webp,image/gif" onChange={e=>{const f=e.target.files?.[0];if(f)uploadImage(f);e.currentTarget.value=""}}/>
 {showAI&&<section className="ai-panel"><div className="panel-head"><strong>Workspace AI</strong><button onClick={()=>setShowAI(false)}>×</button></div><p>{elements.length?`Your board has ${elements.length} objects. Try grouping related notes and connecting decisions with arrows.`:"Add a few ideas and I’ll help you structure the board."}</p><button onClick={()=>setAI("Suggested next step: group your notes into themes, connect dependencies, then turn the strongest theme into an action list.")}>Analyze board</button>{ai&&<div className="ai-result">{ai}</div>}</section>}
 {showComments&&<section className="comments-panel"><div className="panel-head"><strong>Comments</strong><button onClick={()=>setShowComments(false)}>×</button></div><div className="comment-list">{comments.length?comments.map(c=><article key={c.id}><div><b>{c.user}</b><span>{new Date(c.createdAt).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"})}</span></div><p>{c.text}</p><div className="reactions"><button onClick={()=>react(c.id,"👍")}>👍 {c.reactions["👍"]?.length||0}</button><button onClick={()=>react(c.id,"❤️")}>❤️ {c.reactions["❤️"]?.length||0}</button><button onClick={()=>react(c.id,"💡")}>💡 {c.reactions["💡"]?.length||0}</button></div></article>):<p className="empty">No comments yet. Start the conversation.</p>}</div><div className="comment-compose"><textarea value={commentText} onChange={e=>setCommentText(e.target.value)} placeholder="Add a comment…"/><button onClick={addComment}>Post</button></div></section>}
 <footer>Canvasly · collaborative whiteboard · {status}</footer></div>;
}
export default App;
