import { useEffect, useMemo, useRef, useState } from "react";
import type { PointerEvent } from "react";
import "./App.css";

const WS_URL = "wss://canvasly-f0et.onrender.com";
const W = 1200, H = 700;
type Tool="select"|"pen"|"eraser"|"line"|"arrow"|"rectangle"|"circle"|"text"|"sticky";
type P={x:number;y:number};
type El={id:string;type:Exclude<Tool,"select">;points:P[];color:string;size:number;user:string;text?:string;fill?:boolean};
type User={id:string;name:string;color:string;drawing:boolean};
type Msg={type:string;[k:string]:any};
const roomOf=()=>new URLSearchParams(location.search).get("room")?.trim()||"main";
const roomKey=(r:string)=>`canvasly:${r}`;
const authKey="canvasly:account";
const clean=(s:string)=>s.trim().replace(/\s+/g,"-").replace(/[^a-zA-Z0-9_-]/g,"").slice(0,60)||"main";

function App(){
 const canvas=useRef<HTMLCanvasElement>(null), scroll=useRef<HTMLDivElement>(null), ws=useRef<WebSocket|null>(null), els=useRef<El[]>([]), nameRef=useRef("Guest"), clip=useRef<El[]>([]), active=useRef<string|null>(null), start=useRef<P|null>(null), drag=useRef<any>(null), raf=useRef<number|null>(null);
 const [room,setRoom]=useState(roomOf),[roomInput,setRoomInput]=useState(roomOf),[name,setName]=useState("Guest"),[tool,setTool]=useState<Tool>("pen"),[color,setColor]=useState("#111827"),[size,setSize]=useState(4),[fill,setFill]=useState(false),[elements,setElements]=useState<El[]>([]),[selected,setSelected]=useState<string[]>([]),[redo,setRedo]=useState<El[]>([]),[users,setUsers]=useState<User[]>([]),[status,setStatus]=useState("connecting"),[zoom,setZoom]=useState(1),[drawing,setDrawing]=useState(false),[cur,setCur]=useState<P|null>(null),[cursors,setCursors]=useState<Record<string,any>>({}),[modal,setModal]=useState<null|Tool>(null),[modalText,setModalText]=useState(""),[showAI,setShowAI]=useState(false),[ai,setAI]=useState(""),[auth,setAuth]=useState(false),[authMode,setAuthMode]=useState<"login"|"signup">("login"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[space,setSpace]=useState(false),[notice,setNotice]=useState("");
 useEffect(()=>{els.current=elements},[elements]); useEffect(()=>{nameRef.current=name.trim()||"Guest"},[name]);
 const board=(n:El[])=>{els.current=n;setElements(n);try{localStorage.setItem(roomKey(room),JSON.stringify(n))}catch{}};
 const send=(m:object)=>{if(ws.current?.readyState===1)ws.current.send(JSON.stringify(m))};
 const op=(m:object)=>send({...m,opId:crypto.randomUUID()});
 const bounds=(e:El)=>{if(e.type==="circle"){const a=e.points[0],b=e.points.at(-1)||a,r=Math.max(1,Math.hypot(b.x-a.x,b.y-a.y));return{x:a.x-r,y:a.y-r,w:r*2,h:r*2}};if(e.type==="text"){const a=e.points[0];return{x:a.x,y:a.y-e.size*5,w:Math.max(40,(e.text||"").length*e.size*2.2),h:Math.max(24,e.size*6)}};const xs=e.points.map(p=>p.x),ys=e.points.map(p=>p.y);return{x:Math.min(...xs),y:Math.min(...ys),w:Math.max(1,Math.max(...xs)-Math.min(...xs)),h:Math.max(1,Math.max(...ys)-Math.min(...ys))}};
 const draw=(c:CanvasRenderingContext2D,e:El)=>{if(!e.points.length)return;const a=e.points[0],b=e.points.at(-1)||a;c.lineWidth=e.size;c.lineCap="round";c.lineJoin="round";c.strokeStyle=e.type==="eraser"?"#fff":e.color;if(e.type==="text"){c.fillStyle=e.color;c.font=`600 ${Math.max(12,e.size*4)}px Inter,Arial`;(e.text||"").split("\n").forEach((t,i)=>c.fillText(t,a.x,a.y+i*Math.max(16,e.size*5)));return}if(e.type==="sticky"){const x=Math.min(a.x,b.x),y=Math.min(a.y,b.y),w=Math.max(100,Math.abs(b.x-a.x)),h=Math.max(80,Math.abs(b.y-a.y));c.fillStyle=e.color;c.fillRect(x,y,w,h);c.strokeStyle="#0003";c.strokeRect(x,y,w,h);c.fillStyle="#111827";c.font=`600 ${Math.max(12,e.size*3)}px Inter,Arial`;(e.text||"Note").split("\n").forEach((t,i)=>c.fillText(t,x+12,y+26+i*18));return}c.beginPath();if(e.type==="pen"||e.type==="eraser"){c.moveTo(a.x,a.y);e.points.slice(1).forEach(p=>c.lineTo(p.x,p.y));c.stroke();return}if(e.type==="line"){c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.stroke();return}if(e.type==="arrow"){const ang=Math.atan2(b.y-a.y,b.x-a.x),head=Math.max(12,e.size*4);c.moveTo(a.x,a.y);c.lineTo(b.x,b.y);c.moveTo(b.x,b.y);c.lineTo(b.x-head*Math.cos(ang-Math.PI/6),b.y-head*Math.sin(ang-Math.PI/6));c.moveTo(b.x,b.y);c.lineTo(b.x-head*Math.cos(ang+Math.PI/6),b.y-head*Math.sin(ang+Math.PI/6));c.stroke();return}if(e.type==="rectangle"){const x=Math.min(a.x,b.x),y=Math.min(a.y,b.y),w=Math.abs(b.x-a.x),h=Math.abs(b.y-a.y);if(e.fill){c.fillStyle=e.color;c.globalAlpha=.2;c.fillRect(x,y,w,h);c.globalAlpha=1}c.strokeRect(x,y,w,h);return}if(e.type==="circle"){const r=Math.hypot(b.x-a.x,b.y-a.y);if(e.fill){c.fillStyle=e.color;c.globalAlpha=.2;c.beginPath();c.arc(a.x,a.y,r,0,Math.PI*2);c.fill();c.globalAlpha=1}c.beginPath();c.arc(a.x,a.y,r,0,Math.PI*2);c.stroke()}};
 const redraw=()=>{const c=canvas.current,x=c?.getContext("2d");if(!c||!x)return;x.clearRect(0,0,W,H);x.fillStyle="#fff";x.fillRect(0,0,W,H);els.current.forEach(e=>draw(x,e));selected.forEach(id=>{const e=els.current.find(a=>a.id===id);if(!e)return;const b=bounds(e);x.save();x.strokeStyle="#2563eb";x.lineWidth=2;x.setLineDash([6,4]);x.strokeRect(b.x-5,b.y-5,b.w+10,b.h+10);x.setLineDash([]);[[b.x,b.y],[b.x+b.w,b.y],[b.x,b.y+b.h],[b.x+b.w,b.y+b.h]].forEach(([a,d])=>{x.fillStyle="#fff";x.fillRect(a-4,d-4,8,8);x.strokeRect(a-4,d-4,8,8)});x.restore()})};
 useEffect(()=>redraw(),[elements,selected,zoom]);
 useEffect(()=>{let stop=false;try{const c=JSON.parse(localStorage.getItem(roomKey(room))||"null");if(Array.isArray(c)){els.current=c;setElements(c)}}catch{};const connect=()=>{if(stop)return;setStatus("connecting");const s=new WebSocket(WS_URL);ws.current=s;s.onopen=()=>{setStatus("connected");send({type:"join",room,name:nameRef.current})};s.onmessage=e=>{try{const d:Msg=JSON.parse(e.data);if(d.type==="sync"){board(d.elements||[]);return}if(d.type==="presence"){setUsers(d.users||[]);return}if(d.type==="users"){return}if(d.type==="draw")board([...els.current.filter(x=>x.id!==d.element.id),d.element]);if(d.type==="remove")board(els.current.filter(x=>x.id!==d.id));if(d.type==="clear")board([]);if(d.type==="cursor"&&d.id){setCursors(v=>({...v,[d.id]:d}))}if(d.type==="user_left")setCursors(v=>{const n={...v};delete n[d.id];return n})}catch{}};s.onclose=()=>{ws.current=null;if(!stop){setStatus("disconnected");setTimeout(connect,2500)}}};connect();return()=>{stop=true;ws.current?.close()}},[room]);
 const point=(e:PointerEvent<HTMLCanvasElement>):P=>{const r=canvas.current!.getBoundingClientRect();return{x:(e.clientX-r.left)/r.width*W,y:(e.clientY-r.top)/r.height*H}};
 const hit=(p:P)=>{for(let i=els.current.length-1;i>=0;i--){const b=bounds(els.current[i]);if(p.x>=b.x-10&&p.x<=b.x+b.w+10&&p.y>=b.y-10&&p.y<=b.y+b.h+10)return els.current[i]}return null};
 const create=(a:P,b:P,text?:string):El=>({id:crypto.randomUUID(),type:tool,points:[a,b],color,size,user:nameRef.current,text,fill});
 const down=(e:PointerEvent<HTMLCanvasElement>)=>{const p=point(e);e.currentTarget.setPointerCapture(e.pointerId);if(space){drag.current={pan:true,sx:e.clientX,sy:e.clientY,l:scroll.current?.scrollLeft||0,t:scroll.current?.scrollTop||0};return}if(tool==="select"){const h=hit(p);if(h){if(e.shiftKey)setSelected(s=>s.includes(h.id)?s.filter(x=>x!==h.id):[...s,h.id]);else setSelected([h.id]);drag.current={start:p,originals:els.current.filter(x=>selected.includes(x.id)||x.id===h.id)}}else if(!e.shiftKey)setSelected([]);return}if(tool==="text"||tool==="sticky"){setModal(tool);setModalText("");return}setDrawing(true);start.current=p;setCur(p);send({type:"activity",room,drawing:true});if(tool==="pen"||tool==="eraser"){const x=create(p,p);active.current=x.id;board([...els.current,x])}};
 const move=(e:PointerEvent<HTMLCanvasElement>)=>{const p=point(e);if(space&&drag.current?.pan){const s=scroll.current;if(s){s.scrollLeft=drag.current.l-(e.clientX-drag.current.sx);s.scrollTop=drag.current.t-(e.clientY-drag.current.sy)}return}if(tool==="select"&&drag.current?.originals){const dx=p.x-drag.current.start.x,dy=p.y-drag.current.start.y;const ids=new Set(drag.current.originals.map((x:El)=>x.id));board(els.current.map(x=>ids.has(x.id)?{...x,points:x.points.map(q=>({x:q.x+dx,y:q.y+dy}))}:x));return}if(!drawing)return;setCur(p);if((tool==="pen"||tool==="eraser")&&active.current)board(els.current.map(x=>x.id===active.current?{...x,points:[...x.points,p]}:x))};
 const up=()=>{if(space){drag.current=null;return}if(tool==="select"){if(drag.current?.originals)drag.current.originals.forEach((o:El)=>{const n=els.current.find(x=>x.id===o.id);if(n)op({type:"draw",room,element:n})});drag.current=null;return}if(!drawing)return;if(start.current&&cur&&tool!=="pen"&&tool!=="eraser"){const x=create(start.current,cur);board([...els.current,x]);op({type:"draw",room,element:x})}else if(active.current){const x=els.current.find(a=>a.id===active.current);if(x)op({type:"draw",room,element:x})}active.current=null;start.current=null;setCur(null);setDrawing(false);send({type:"activity",room,drawing:false})};
 const addModal=()=>{if(!modalText.trim())return;const a=start.current||{x:180,y:150},b=modal==="text"?{x:a.x+Math.max(80,modalText.length*size*2.2),y:a.y+30}:{x:a.x+230,y:a.y+150};const x=create(a,b,modalText.trim());board([...els.current,x]);op({type:"draw",room,element:x});setModal(null);setModalText("")};
 const remove=()=>{if(!selected.length)return;selected.forEach(id=>op({type:"remove",room,id}));board(els.current.filter(x=>!selected.includes(x.id)));setSelected([])};
 const copy=()=>{clip.current=els.current.filter(x=>selected.includes(x.id)).map(x=>({...x,points:x.points.map(p=>({...p}))}))};
 const paste=()=>{const a=clip.current.map(x=>({...x,id:crypto.randomUUID(),user:nameRef.current,points:x.points.map(p=>({x:p.x+30,y:p.y+30}))}));if(!a.length)return;board([...els.current,...a]);setSelected(a.map(x=>x.id));a.forEach(x=>op({type:"draw",room,element:x}))};
 const undo=()=>{const mine=els.current.filter(x=>x.user===nameRef.current);const x=mine.at(-1);if(!x)return;removeOne(x.id);setRedo(r=>[...r,x])}; const removeOne=(id:string)=>{op({type:"remove",room,id});board(els.current.filter(x=>x.id!==id));setSelected([])}; const redoOne=()=>{const x=redo.at(-1);if(!x)return;board([...els.current,x]);op({type:"draw",room,element:x});setRedo(r=>r.slice(0,-1))};
 const aiText=()=>{const counts=elements.reduce((a,e)=>(a[e.type]=(a[e.type]||0)+1,a),{} as Record<string,number>);const keys=Object.keys(counts);if(!keys.length)return "Your board is empty. Try adding a goal, idea, decision, or next step.";const tips=[];if(counts.sticky)tips.push(`You have ${counts.sticky} sticky note${counts.sticky>1?"s":""}. Group them into themes and mark the top 3 actions.`);if(counts.text)tips.push(`There are ${counts.text} text items. Add arrows between related ideas to show flow.`);if(counts.arrow||counts.line)tips.push("Your board has connections. Consider adding a clear Start → Process → Result flow.");tips.push(`Canvas contains ${elements.length} objects across ${keys.join(", ")}.`);return tips.join(" ")};
 useEffect(()=>{const k=(e:KeyboardEvent)=>{const m=e.ctrlKey||e.metaKey;if(e.code==="Space"&&!e.repeat){setSpace(true);e.preventDefault()}if(m&&e.key.toLowerCase()==="z"){e.preventDefault();undo()}else if(m&&e.key.toLowerCase()==="y"){e.preventDefault();redoOne()}else if(m&&e.key.toLowerCase()==="c"&&selected.length){e.preventDefault();copy()}else if(m&&e.key.toLowerCase()==="v"){e.preventDefault();paste()}else if(m&&e.key.toLowerCase()==="d"){e.preventDefault();copy();setTimeout(paste,0)}else if((e.key==="Delete"||e.key==="Backspace")&&selected.length){e.preventDefault();remove()}};const u=(e:KeyboardEvent)=>{if(e.code==="Space")setSpace(false)};addEventListener("keydown",k);addEventListener("keyup",u);return()=>{removeEventListener("keydown",k);removeEventListener("keyup",u)}},[selected,redo,elements]);
 const switchRoom=()=>{const r=clean(roomInput);history.pushState({},"",`?room=${encodeURIComponent(r)}`);setRoom(r);setSelected([])};const share=async()=>{const u=`${location.origin}${location.pathname}?room=${encodeURIComponent(room)}`;try{await navigator.clipboard.writeText(u);setNotice("Room link copied") }catch{setNotice(u)}};const exportPNG=()=>{const a=document.createElement("a");a.download=`canvasly-${room}.png`;a.href=canvas.current!.toDataURL();a.click()};const fit=()=>setZoom(Math.min(1.5,Math.max(.5,((scroll.current?.clientWidth||W)-40)/W)));
 const tools:[Tool,string][]=[["select","Select"],["pen","Pen"],["eraser","Eraser"],["line","Line"],["arrow","Arrow"],["rectangle","Rect"],["circle","Circle"],["text","Text"],["sticky","Sticky"]];
 const account=useMemo(()=>{try{return JSON.parse(localStorage.getItem(authKey)||"null")}catch{return null}},[auth]);
 const doAuth=()=>{if(!email||password.length<4){setNotice("Use an email and 4+ character password");return}const a={email,password};localStorage.setItem(authKey,JSON.stringify(a));setAuth(true);setName(email.split("@")[0].slice(0,20)||"Guest");setNotice(authMode==="signup"?"Account created":"Signed in")};
 if(!auth)return <div className="auth-screen"><div className="auth-card"><div className="logo">✦</div><h1>Canvasly</h1><p>Real-time collaborative workspace</p><div className="auth-tabs"><button className={authMode==="login"?"active":""} onClick={()=>setAuthMode("login")}>Sign in</button><button className={authMode==="signup"?"active":""} onClick={()=>setAuthMode("signup")}>Create account</button></div><input placeholder="Email" value={email} onChange={e=>setEmail(e.target.value)}/><input placeholder="Password" type="password" value={password} onChange={e=>setPassword(e.target.value)} onKeyDown={e=>e.key==="Enter"&&doAuth()}/><button className="primary" onClick={doAuth}>{authMode==="signup"?"Create account":"Sign in"}</button><small>Demo auth for submission • production auth can be connected to Supabase Auth</small></div></div>;
 return <div className="app"><header className="topbar"><div className="brand"><div className="logo">✦</div><div><h1>Canvasly</h1><span>Collaborative canvas</span></div></div><div className="connection"><i className={status}/>{status}</div><div className="top-actions"><input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name"/><input className="room-input" value={roomInput} onChange={e=>setRoomInput(e.target.value)} onKeyDown={e=>e.key==="Enter"&&switchRoom()}/><button onClick={switchRoom}>Join</button><button onClick={share}>Share</button><button onClick={()=>setShowAI(v=>!v)} className="ai-btn">✦ AI</button><button onClick={()=>{localStorage.removeItem(authKey);setAuth(false)}}>Sign out</button></div></header>
 <nav className="toolbar"><div className="tool-group">{tools.map(([id,label])=><button key={id} className={tool===id?"tool active":"tool"} onClick={()=>setTool(id)}>{label}</button>)}</div><span className="divider"/><label>Color <input type="color" value={color} onChange={e=>setColor(e.target.value)}/></label><label className="size">Size {size}<input type="range" min="1" max="18" value={size} onChange={e=>setSize(+e.target.value)}/></label><label><input type="checkbox" checked={fill} onChange={e=>setFill(e.target.checked)}/> Fill</label><span className="divider"/><button onClick={undo}>↶ Undo</button><button onClick={redoOne}>↷ Redo</button><button onClick={copy}>Copy</button><button onClick={paste}>Paste</button><button onClick={remove}>Delete</button><button onClick={()=>setZoom(z=>Math.max(.5,z-.1))}>−</button><b>{Math.round(zoom*100)}%</b><button onClick={()=>setZoom(z=>Math.min(2,z+.1))}>+</button><button onClick={fit}>Fit</button><button onClick={exportPNG}>Export PNG</button></nav>
 {showAI&&<aside className="ai-panel"><strong>✦ Canvasly AI Assistant</strong><p>{ai||"Ask AI for a quick board review."}</p><button onClick={()=>setAI(aiText())}>Analyze board</button><button onClick={()=>setAI("Suggested next steps: define the goal → group ideas → choose priorities → connect dependencies → assign owners → export/share the final board.")}>Suggest workflow</button><button onClick={()=>setAI("Try: one sticky per idea, short labels, arrows for relationships, and a final decision box. Keep the most important path visually central.")}>Improve layout</button></aside>}
 <main className="workspace"><div className="canvas-card"><div className="canvas-head"><span>Room <b>#{room}</b></span><span>{users.length||1} collaborator{users.length===1?"":"s"} • {elements.length} objects</span></div><div className="canvas-scroll" ref={scroll}><div className="stage" style={{width:W*zoom,height:H*zoom}}><canvas ref={canvas} width={W} height={H} className="canvas" style={{width:W*zoom,height:H*zoom}} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerLeave={up}/>{Object.values(cursors).map((c:any)=><div key={c.id} className="remote" style={{left:c.x*zoom,top:c.y*zoom,"--c":c.color} as any}>➤ <span>{c.name}</span></div>)}</div></div></div></main>
 <footer><span>⌨️ Space + drag to pan • Ctrl/Cmd Z/Y/C/V/D • Delete</span><span>Secure rooms • realtime sync • persistent board</span></footer>
 {modal&&<div className="modal-backdrop"><div className="modal"><h3>{modal==="text"?"Add text":"Add sticky note"}</h3><textarea autoFocus value={modalText} onChange={e=>setModalText(e.target.value)} placeholder={modal==="text"?"Type your text…":"Write your note…"}/><div><button onClick={()=>setModal(null)}>Cancel</button><button className="primary" onClick={addModal}>Add</button></div></div></div>}
 {notice&&<button className="toast" onClick={()=>setNotice("")}>{notice}</button>}
 </div>;
}
export default App;
